spring:
  primary:
    datasource:
      password: mysecretpassword
      username: postgres
      driver: org.postgresql.Driver
      url: jdbc:postgresql://192.168.0.12:5432/postgres
  replica:
    datasource:
      password: mysecretpassword
      username: postgres
      driver: org.postgresql.Driver
      url: jdbc:postgresql://192.168.0.12:5432/postgres
