spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      auto-offset-reset: earliest
    topics:
      wordcount-input: wordcount-input
      wordcount-output: wordcount-output
      hobbit: hobbit
    streams:
      application-id: streams-app

management:
  endpoint:
    health:
      show-details: ALWAYS
  health:
    binders:
      enabled: true

logging:
  level:
    root: INFO
    org.apache.kafka: ERROR
    com.example.kafkastreams: DEBUG
