spring.application.name=kafka-replying

spring.kafka.consumer.group-id=products-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.missingTopicsFatal=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.topic.request-topic=request-topic
spring.kafka.topic.requestreply-topic=requestreply-topic
spring.kafka.consumergroup=requestreplygroup

server.port=8080

logging.level.root=INFO
logging.level.org.apache.kafka=ERROR
logging.level.com.example.kafkareplying=DEBUG
